apiVersion: v1
kind: Service
metadata:
  name: pv-with-health-service
  labels:
    app: pv-with-health-service
spec:
  selector:
    app: pv-with-health
    task: pv-with-health
  type: LoadBalancer
  ports:
    - port: 5000
      targetPort: 5000
      protocol: TCP
  # type: NodePort
  # ports:
  #   - port: 5000
  #     targetPort: 5000
  #     nodePort: 31005
  #     protocol: TCP
