apiVersion: v1
kind: Service
metadata:
  name: pv-with-health-service
  labels:
    app: pv-with-health-service
spec:
  selector:
    app: pv-with-health
  ports:
    - name: http
      port: 5000

---
kind: Ingress
apiVersion: networking.k8s.io/v1beta1
metadata:
  name: pv-with-health-ingress
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web

spec:
  rules:
    - host: pv.k8s.local
      http:
        paths:
          - path: /
            backend:
              serviceName: pv-with-health-service
              servicePort: 5000
          - path: /health
            backend:
              serviceName: pv-with-health-service
              servicePort: 5000
