version: "3.7"
services:
  pic-viewer:
    image: ${REPOSITORY:-ntdtfr}/pic-viewer:${VERSION:-latest}
    environment:
      # - FLASK_APP=pic-viewer
      # production or development
      - FLASK_ENV=development
      - FLASK_RUN_HOST=0.0.0.0
    ports:
      - 5001:5000
    networks:
      - traefik-net
    healthcheck:
      test: ["CMD", "curl", "-fs", "http://pic-viewer:5000/health"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
    deploy:
      mode: replicated
      replicas: 2
      placement:
        constraints:
          - node.role==manager
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
        max_attempts: 5
      # resources:
      #   limits:
      #     cpus: "0.2"
      #     memory: 200M
      #   reservations:
      #     cpus: "0.1"
      #     memory: 100M
networks:
  traefik-net:
    external: true
