version: "3.7"
services:
  pic-viewer:
    image: ${REPOSITORY:-ntdtfr}/pic-viewer:${VERSION:-latest}
    environment:
      # - FLASK_APP=pic-viewer
      # production or development
      - FLASK_ENV=production
      - FLASK_RUN_HOST=0.0.0.0
    # ports:
    #   - 5001:5000
    networks:
      - traefik-net
    healthcheck:
      test: ["CMD", "curl", "-fs", "http://localhost:5000/health"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
    deploy:
      mode: replicated
      replicas: 1
      labels:
        # Traefik v2.x
        # https://docs.traefik.io/providers/docker/
        - traefik.enable=true
        - traefik.http.routers.pic-viewer.rule=Host(`pic-viewer.${DOMAIN:-swarm.lan}`)
        - traefik.http.services.pic-viewer-service.loadbalancer.server.port=5000
        - traefik.http.services.pic-viewer-service.loadbalancer.healthcheck.path=/health
        - traefik.http.services.pic-viewer-service.loadbalancer.healthcheck.port=5000
        - traefik.http.middlewares.latency-check.circuitbreaker.expression=LatencyAtQuantileMS(50.0) > 100
      placement:
        constraints:
          - node.role==worker
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
        max_attempts: 5
      resources:
        limits:
          cpus: "0.2"
          memory: 200M
      #   reservations:
      #     cpus: "0.1"
      #     memory: 100M
networks:
  traefik-net:
    external: true
